services:
  - redis-server
language: python
python:
  - "2.7"
install:
  - travis_retry pip install tox
script: tox -e $TOX_ENV
env:
  - TOX_ENV=py27-sentry821
  - TOX_ENV=py27-sentry822
  - TOX_ENV=py27-sentry9
  - TOX_ENV=py27-sentry91
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: __token__
  password:
    secure: fRzemMaGTlmpQ6cW/uyKX2b4+dlot0AhwRYwAVHyBZ5XB/Uh/T/gQdHZGFFi7/V4RERst+jNdIT/fbZt6ZGVppayyQ7103s4fo2vHBrSCFEOqAHO6hldKKrIecTbnk5xHAC/c7c8He3DURc3g3JgIq8GkLTXAcc48R3M/0P3qBOTEONaet3WGpPwvFc7flQWNuzlcSNVtqDkasY72rmJw9g7qxBM9Udlemd7Oyv0y9z4t4FcbioILzW3r7x5EoBM55bmdei6Uxj2+65b3rlBr4W/er33yHWbp7QLO7onb0CCv6klTJ5Usufn6lvFAO9YTzx3VA7VNyqKVauzhi5LKP+RNkD17QTxRVqqMr47VCUyONoNYApqC65/7HvyJMRhcSukGlIAMk33sDY1Iq6pHOZaTmO7JaPJ6bxxqAzlimw98MBSbm4gphsM8Uu54oGbTA3Uw3P8wuvPj4n0UHUPzvdjWqPU09zSst9RTjZMgHa3qL5Rw6OWC3BoTOZ+RyadPg/o6+zn19pz0DtxOiQWhFI6NJ9ntTcb3sYsS02U6qFn1pQEqIAnyENzYGjYaHSHC45XMWZA2HDt9HXv/TSe02wXXKkng+DDo5JJvYVQJCYitSrv7EywcVpU2yzt3pDRYChNk9dE50HBrE/TUZ9noTHiP+q6txqQKxWlqJvybhM=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
  distributions: sdist bdist_wheel
